- plugins/resource_search_plugin/Link_parsing/Link_parsing.py
- plugins/resource_search_plugin/Link_parsing/core/login_core.py
- run/streaming_media/bilibili.py
> 一点致命bug的修复

- main.py
- plugins/resource_search_plugin/Link_parsing/music_parsing/core/draw.py
- plugins/resource_search_plugin/Link_parsing/music_parsing/music_link_parsing.py
- plugins/resource_search_plugin/Link_parsing/music_parsing/netease_music.py
- run/streaming_media/music_link_parsing.py
> 增加网易云音乐卡片解析

- plugins/resource_search_plugin/Link_parsing/Link_parsing.py
- plugins/resource_search_plugin/Link_parsing/core/common.py
- plugins/resource_search_plugin/Link_parsing/core/draw.py
- plugins/resource_search_plugin/engine_search.py
- run/groupManager/wifeyouwant.py
> 新增世伊Gal小站的链接解析以及修复bug

- plugins/aiDraw/modelscope_text2img.py
- run/aiDraw.py
> modelscope绘图修改

- plugins/aiDraw/wildcard.py
> 修改wildcard匹配规则

- plugins/aiDraw/aiDraw.py
> sampler获取错误bug

- plugins/aiDraw/aiDraw.py
> 修复潜在的报错可能性

- .idea/.gitignore
- .idea/Eridanus.iml
- .idea/inspectionProfiles/profiles_settings.xml
- .idea/misc.xml
- .idea/modules.xml
- .idea/vcs.xml
- plugins/aiDraw/modelscope_text2img.py
> 正则表达式匹配流式响应中返回的图片URL

- run/aiDraw.py
> 加自动撤回，防止刷屏

- plugins/aiDraw/aiDraw.py
- plugins/aiDraw/setu_moderate.py
> 适配有些加了--api-auth 账号:密码 启动参数的sd api，在配置文件的sdapi或审核api中填写  网址 账号:密码  来自动识别

- run/system_plugin/func_collection.py
> 使用函数调用取消 amsr 订阅时出错

- run/group_fun/config.yaml
- run/group_fun/wifeyouwant.py
> 新增今日管理、今日群友功能

- developTools/adapters/http_adapter.py
- developTools/adapters/websocket_adapter.py
- developTools/event/base.py
- developTools/event/bus.py
- developTools/event/eventFactory.py
- developTools/message/message_components.py
- framework_common/database_util/User.py
- framework_common/database_util/llmDB.py
- framework_common/framework_util/func_map.py
- framework_common/framework_util/websocket_fix.py
- framework_common/utils/convert_func_calling.py
- framework_common/utils/langdect.py
- framework_common/utils/translate.py
- framework_common/utils/utils.py
- run/basic_plugin/service/life_service.py
> remove useless import.

- run/group_fun/service/lex_burner_Ninja.py
> Fix An error

- run/acg_infromation/bangumi.py
> Some Wrong To The Developers

- developTools/adapters/http_adapter.py
- developTools/event/events.py
- developTools/interface/http_sendMes.py
- developTools/utils/cq_code_handler.py
- developTools/utils/logger.py
- framework_common/database_util/Group.py
- framework_common/framework_util/func_map_loader.py
- framework_common/manshuo_draw/core/util/json_check.py
- framework_common/manshuo_draw/manshuo_draw.py
- framework_common/utils/ai_translate.py
- run/acg_infromation/blue_archive.py
- run/streaming_media/service/Link_parsing/Link_parsing.py
> Update logger.py(not finished)

- framework_common/manshuo_draw/core/classic_collection/initialize.py
- framework_common/manshuo_draw/data/config/save_config.yml
- tool.py
> 将绘图默认配置文件修改为yml

- framework_common/manshuo_draw/core/classic_collection/Games.py
- framework_common/manshuo_draw/core/classic_collection/avatar.py
- framework_common/manshuo_draw/core/classic_collection/backdrop.py
- framework_common/manshuo_draw/core/classic_collection/basic_img_set.py
- framework_common/manshuo_draw/core/classic_collection/img.py
- framework_common/manshuo_draw/core/classic_collection/layer.py
- framework_common/manshuo_draw/core/classic_collection/text.py
- framework_common/manshuo_draw/core/deal_img.py
- framework_common/manshuo_draw/core/util/common.py
- framework_common/manshuo_draw/core/util/download_img.py
- framework_common/manshuo_draw/core/util/img_deal.py
- framework_common/manshuo_draw/core/util/text_deal.py
- framework_common/manshuo_draw/data/config/save_config.yml
- framework_common/manshuo_draw/manshuo_draw.py
- run/group_fun/number_speeches.py
- run/streaming_media/service/Link_parsing/Link_parsing.py
> 优化绘图框架性能，将所有请求与操作修正为异步执行

- run/anime_game_service/SteamSnooping.py
- run/anime_game_service/config.yaml
- run/anime_game_service/service/SteamSnooping/SteamSnooping.py
- run/anime_game_service/service/SteamSnooping/__init__.py
- run/anime_game_service/service/SteamSnooping/steam.py
> Steam视奸功能更新

- run/group_fun/wifeyouwant.py
> 修复 透热门群友 的相关bug

- run/group_fun/wifeyouwant.py
[修复 napcat 与 拉格朗日 部分数据不兼容问题](https://github.com/AOrbitron/Eridanus/commit/35adabe16dba9d3a8c5965a71c18eefe40a64bf1)
> 修复 napcat 与 拉格朗日 部分数据不兼容问题

- run/groupManager/self_Manager.py
> 缓存文件递归删子文件夹

- run/ai_generated_art/gemini_nano_banana.py
Refactor API payload to include safety settings and improve error handling for image processing.
> Enhance API payload and error handling
